name: CI

on:
  pull_request:

jobs:
  lint:
    
    runs-on: ubuntu-16.04
    steps:
      - uses: stefanoeb/eslint-action@1.0.2
        
      - name: Run a code check with ESLint
        run: npm install && npm run lint
 
